layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

repositories:
  - ForeignIpsum
  - Homesick
  - desktop-test
  - Juice
  - MacPlug
  

projects:
  # sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 0
  exclude:
    forks:
    projects: – license, - vineconvert
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: 3raxton
  # medium: @your_username
  # stackoverflow: your_user_id
  twitter: 3raxton
  # youtube: your_username

topics:
  - name: Sketch
    web_url: https://github.com/topics/sketch
    image_url: https://raw.githubusercontent.com/github/explore/a5995564b5ff71c41da080abc49f1ba4132127c1/topics/sketch/sketch.png

  - name: iOS
    web_url: https://github.com/topics/sketch
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/ios/ios.png

  - name: HTML
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/html/html.png
